Task 5, this is the python exceptions
